### ISSUE TITLE
Can't start app, Wii U can't find steam or any application.

### ISSUE THREAD

**Issue by GVKAWESOME** [GaryOderNichts/moonlight-wiiu#10]
Hi I am running sunshine on my main computer which runs Linux (Arch Linux) but no matter what application I specify, moonlight-wiiu can't find the application, even if the application is already started.

What should I specify in the app=

I have already tried to do yuzu and steam. 

Is there a way to just get to the desktop?

**Comment by GaryOderNichts** [comment]
If you're using sunshine you can add application names in the sunshine web gui.

**Comment by GVKAWESOME** [comment]
Makes sense. I haven't tried adding steam through Sunshine. But the wii u just complains that it can't find steam.

Guess I will try adding the application through sunshine. Then I will report back.

Thank you

**Comment by GVKAWESOME** [comment]
Thank you very much Gary,

Didn't know why I haven't tried specifying the application on both sunshine and moonlight.

Well guess I just learned something today. Thank you and have a great day
