### ISSUE TITLE
v1.3 stuck at moonlight.rpx

### ISSUE THREAD

**Issue by Moonlitius** [GaryOderNichts/moonlight-wiiu#11]
I downloaded the latest release (v1.3.) added the GFE IP to the conf file but whenever I start it from the homebrew channel it get's stuck at "loading file moonlight.rpx" and I need to turn of the WiiU by holding the power button.

**Comment by L1ghtingBolt** [comment]
Why did you close this? I have the same issue

**Comment by ICURSEDANGEL** [comment]
> Why did you close this? I have the same issue

Same here, have you found a fix for it yet.

**Comment by GaryOderNichts** [comment]
Don't use the Homebrew Launcher V
Channel. Load HBL through the Mii Maker instead.

**Comment by ICURSEDANGEL** [comment]
> Don't use the Homebrew Launcher V Channel. Load HBL through the Mii Maker instead.

That worked thank you for your reply.

**Comment by L1ghtingBolt** [comment]
That worked for me.
