### ISSUE TITLE
Moonlight Crashing on wii u.

### ISSUE THREAD

**Issue by quonkies** [GaryOderNichts/moonlight-wiiu#12]
My wii u has been crashing at the moonlight ever since i've ever got it. So basically everytime, I open the hb launcher then make sure Nvidia's shield streaming's on, I already have paired it so I just press stream and everything's going good and then randomly crashes out of nowhere, is there a way I can fix this for this?

**Comment by quonkies** [comment]
> Does it start to stream and then crash after a little while or just crash before it starts streaming?

it streams, and then after a while it crashes, input from the gamepad works well tho

**Comment by aaronjamt** [comment]
Hmm, that sounds like either a network issue or a server issue. Is the Wii U connected via WiFi or Ethernet? Is the Nvidia Shield on the same network and, if so, how is it connected?

**Comment by aaronjamt** [comment]
Also check to see if gamepad input continues to work after it crashes. If so, it hasn't _completely_ crashed, just the audio and/or video feeds have stopped.

**Comment by quonkies** [comment]
> Hmm, that sounds like either a network issue or a server issue. Is the Wii U connected via WiFi or Ethernet? Is the Nvidia Shield on the same network and, if so, how is it connected?

it is connected via WiFi, and i'm running my pc on Ethernet but my console on WiFi (same network) it is the nvidia shield.

**Comment by quonkies** [comment]
> Also check to see if gamepad input continues to work after it crashes. If so, it hasn't _completely_ crashed, just the audio and/or video feeds have stopped.

It completely crashes, gamepad non-responsive.

**Comment by aaronjamt** [comment]
Can you check what version of GeForce Experience (GFE) the Shield is running? I'm not very familiar with that system. You can try older versions of Moonlight-WiiU [on the Releases page](https://github.com/GaryOderNichts/moonlight-wiiu/releases) such as [v1.2](https://github.com/GaryOderNichts/moonlight-wiiu/releases/tag/wiiu-v1.2) to see if they also have the same issue. I didn't have disconnection/crashing issues when connecting to Moonlight on a PC (Wii U on WiFi, PC on Ethernet, I also tried with port forwarding outside of my network and it worked fine). I don't know if @GaryOderNichts has any debug build(s) available to give more information about the connection, if so you can try that. I would also try to connect to your PC rather than the Shield to see if that makes a difference.

**Comment by quonkies** [comment]
> Can you check what version of GeForce Experience (GFE) the Shield is running? I'm not very familiar with that system. You can try older versions of Moonlight-WiiU [on the Releases page](https://github.com/GaryOderNichts/moonlight-wiiu/releases) such as [v1.2](https://github.com/GaryOderNichts/moonlight-wiiu/releases/tag/wiiu-v1.2) to see if they also have the same issue. I didn't have disconnection/crashing issues when connecting to Moonlight on a PC (Wii U on WiFi, PC on Ethernet, I also tried with port forwarding outside of my network and it worked fine, although that was using my fork of the project which is now about 100 commits behind so I don't know if changes since then have affected anything). I don't know if @GaryOderNichts has any debug build(s) available to give more information about the connection, if so you can try that. I would also try to connect to your PC rather than the Shield to see if that makes a difference.

hey aaron, so basically i tried the older version, the 1.2v and everything's working! it's just the latest version of it that's not working, confusing
thank you for helping me debugging this :D

**Comment by aaronjamt** [comment]
Ok, great! It might be a good idea to try to debug this further at some point to find and fix this regression but I'm glad that works for you.

**Comment by GaryOderNichts** [comment]
Can you test if the latest nightly still has that issue?
Download the artifact from here: https://github.com/GaryOderNichts/moonlight-wiiu/actions/runs/1808705191

**Comment by quonkies** [comment]
> Can you test if the latest nightly still has that issue? Download the artifact from here: https://github.com/GaryOderNichts/moonlight-wiiu/actions/runs/1808705191

Hey Gary, I've actually tried it again and I'm surprised that it works fine now! Even that one issue in the 1.2v that disconnects randomly to homebrew, thank you!

**Comment by quonkies** [comment]
> Can you test if the latest nightly still has that issue? Download the artifact from here: https://github.com/GaryOderNichts/moonlight-wiiu/actions/runs/1808705191

Hey Gary, I've actually tried it again and I'm surprised that it works fine now! Even that one issue in the 1.2v that disconnects randomly to homebrew, thank you!
