### ISSUE TITLE
[BUG] Only 2 controllers work at a time

### ISSUE THREAD

**Issue by ZorroHedgehog** [GaryOderNichts/moonlight-wiiu#15]
Only 2 controllers work at a time. Does anybody know how to fix this?

**Comment by GaryOderNichts** [comment]
Can you test out the [latest nightly build](https://github.com/GaryOderNichts/moonlight-wiiu/suites/6212556366/artifacts/219602464) and see if the problem still exists? (You need to be logged in to download artifacts)
