### ISSUE TITLE
Disconnectswhen trying to stream from sunshine

### ISSUE THREAD

**Issue by Guttles** [GaryOderNichts/moonlight-wiiu#17]
I use arch Linux and have sunshine setup to stream games. It works perfectly on my laptop and home theatre PC, but when I try to use it on wiiu I get a starting stream message and then a disconnected error. I'm using a wired connection for the wiiu and my main PC. It launches Steam BP on my rig, but doesn't display anything on the gamepad or TV.

**Comment by All-StarsPixel** [comment]
simular here. Im trying to get better 3ds emulation on the steam deck

**Comment by GaryOderNichts** [comment]
Your bitrate is probably too high and your network connection can't keep up (see the newly added [Troubleshooting section](https://github.com/GaryOderNichts/moonlight-wiiu#troubleshooting)).
You can also try the latest [v1.6 release](https://github.com/GaryOderNichts/moonlight-wiiu/releases/tag/wiiu-v1.6) which comes with networking improvements.
