### ISSUE TITLE
Add an exit stream button combo

### ISSUE THREAD

**Issue by HbSpartanIV** [GaryOderNichts/moonlight-wiiu#18]
I appreciate the work you did porting this to the Wii U but if it is possible to add a button combo to exit the stream in the case of directly streaming the desktop cause there is no apparent way to do so except resetting the console.

**Comment by GaryOderNichts** [comment]
You can exit the stream by pressing down the home button for a few seconds.

**Comment by dude98** [comment]
the holding home button exit is kinda annoying if you use steam since steam has guide button combos for a couple things.
