### ISSUE TITLE
Problem with the command: docker run -it --rm -v ${PWD}:/project moonlightbuilder make

### ISSUE THREAD

**Issue by Special-Niewbie** [GaryOderNichts/moonlight-wiiu#2]
Hello @GaryOderNichts ,

I don't know if it's only my problem or somenthig strange with the command. Once installed Doker, the first command it works, but the below second command it gives the error (any idea?):

`docker run -it --rm -v ${PWD}:/project moonlightbuilder make`

`docker: Error response from daemon: create ${PWD}: "${PWD}" includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help`

As you can see It's somenthing related to the loval volume name **${PWD}** 

Thank you ,
Cris
```

**Comment by GaryOderNichts** [comment]
Try using `docker run -it --rm -v "%cd%":/project moonlightbuilder make` instead.

**Comment by Special-Niewbie** [comment]
> 
> 
> Try using `docker run -it --rm -v "%cd%":/project moonlightbuilder make` instead.

Morning,

good news, really thanks, with this command now the build process will work. 

But it's not finished yet the error.....

There is an error on `AppVersionQuad`, it goes to create the `.elf` file and then it will retrieve the process because it gives the following error:
```
/project/third_party/moonlight-common-c/src/InputStream.c:647: undefined reference to AppVersionQuad
/opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld: /project/third_party/moonlight-common-c/src/InputStream.c:647: undefined reference to AppVersionQuad
/opt/devkitpro/devkitPPC/bin/../lib/gcc/powerpc-eabi/10.2.0/../../../../powerpc-eabi/bin/ld: /project/third_party/moonlight-common-c/src/InputStream.c:670: undefined reference to AppVersionQuad
collect2: error: ld returned 1 exit status
/opt/devkitpro/wut/share/wut_rules:44: recipe for target /project/moonlight.elf failed
make[1]: *** [/project/moonlight.elf] Error 1
Makefile:116: recipe for target build failed
make: *** [build] Error 2
```

**Comment by GaryOderNichts** [comment]
This was actually caused by Windows' case insensitive file system.
Try building with commit https://github.com/GaryOderNichts/moonlight-wiiu/commit/fbe5d5339933689ee585442b9f0ec277d71c9013 again.

**Comment by Special-Niewbie** [comment]
Hi Gary,

I'm back, YES it works now!!!
The Building process it's done.

Really thanks,
Cris
