### ISSUE TITLE
Can't find app Steam

### ISSUE THREAD

**Issue by TheEPICArt** [GaryOderNichts/moonlight-wiiu#20]
When I click b to start streaming, it gives me the error, "Can't find app Steam". Any help?

**Comment by dude98** [comment]
you need to have a program in either sunshine or geforce gamestream labeled "Steam", otherwise it will give you that error. i just opened sunshine and made a blank one called steam so it opens my desktop.

**Comment by MegaRaptor123** [comment]
> you need to have a program in either sunshine or geforce gamestream labeled "Steam", otherwise it will give you that error. i just opened sunshine and made a blank one called steam so it opens my desktop.

I know this is late but how?

**Comment by jdfr228** [comment]
Sunshine by default comes with "Steam BigPicture" set up as its only application.  In the Sunshine configuration, change this to just "Steam" if that's what you actually want to launch.

**Comment by GaryOderNichts** [comment]
I added this to a new [troubleshooting section](https://github.com/GaryOderNichts/moonlight-wiiu#cant-find-app-steam).

**Comment by ZzzZ25871** [comment]
Hi, there's a solution, in the moonlight.conf file, theres a part that says something like "## Default started application on host
app = Steam", so you just have to delete the ## and replace the word "Steam" with "Desktop"

**Comment by tupuetapeter-ops** [comment]
Hi, there's a solution, in the moonlight.conf file, theres a part that says something like "## Default started application on host
app = Steam", so you just have to delete the ## and replace the word "Steam" with "Desktop"
but i say can't find app Desktop
