### ISSUE TITLE
Stuck on "Starting stream..." - Wont connect

### ISSUE THREAD

**Issue by blitz2kx** [GaryOderNichts/moonlight-wiiu#27]
Having a new issue with client - I can pair perfectly fine, but when I start the stream it just stays stuck with "Starting stream...".

I can quit out of moonlight by continuously pressing the home button on the Wii U Gamepad.

I have tried -
Deleting config and keys for moonlight.
Removing all "Shield" devices in Geforce Experience & repairing Wii U

Running latest Nvidia drivers+Geforce Experience. No significant changes to network, host, or Wii U. I am somewhat at a stalemate.

Thank you.

**Comment by Max-Trueby** [comment]
Same here 🙋🏼‍♂️

**Comment by All-StarsPixel** [comment]
ill try the first one. im trying to connect to a steam deck for proper 3ds emulation

**Comment by GaryOderNichts** [comment]
Your bitrate is probably too high and your network connection can't keep up (see the newly added [Troubleshooting section](https://github.com/GaryOderNichts/moonlight-wiiu#troubleshooting)).
You can also try the latest [v1.6 release](https://github.com/GaryOderNichts/moonlight-wiiu/releases/tag/wiiu-v1.6) which comes with networking improvements.
