### ISSUE TITLE
keeps flashing between big picture mode and the game every couple of frames, makes it crash and is unplayable 

### ISSUE THREAD

**Issue by Valllaion** [GaryOderNichts/moonlight-wiiu#29]
Not sure what's causing this, is there a way for it to not launch into big picture mode?

**Comment by dude98** [comment]
that's geforce experience causing it, since geforce automatically opens big picture, but the new steam big picture doesn't work right with geforce experience, it's not something that can be fixed on this end i think.

you might have to unpair geforce and use moonlight instead.
