### ISSUE TITLE
GFE 3.22 incompatibility 

### ISSUE THREAD

**Issue by cgutman** [GaryOderNichts/moonlight-wiiu#3]
To support GFE 3.22 (which was just officially released today), you’ll have to update moonlight-common-c from upstream https://github.com/moonlight-stream/moonlight-common-c

My apologies for introducing yet more little-endian dependencies. Unfortunately I didn’t have time to come up with an endianness solution. It was a huge lift just to get it working at all.

**Comment by GaryOderNichts** [comment]
Fixed with version 1.1.
I also moved the Wii U changes of moonlight-common-c to a [submodule](https://github.com/GaryOderNichts/moonlight-common-c) now.
