### ISSUE TITLE
Doesnt Work on Aroma?

### ISSUE THREAD

**Issue by Jaden360lol** [GaryOderNichts/moonlight-wiiu#33]
When i use on aroma and sunshine it just says pairing failed and pairing code does not fit on screen

**Comment by GaryOderNichts** [comment]
This should work fine on aroma and your issues seems unrelated. The latest [version 1.6 release](https://github.com/GaryOderNichts/moonlight-wiiu/releases/tag/wiiu-v1.6) also comes with a .wuhb and several fixes though.
