### ISSUE TITLE
Moonlight freezing/crashing on Steam Big Picture when entering library or store, or other heavy visual areas

### ISSUE THREAD

**Issue by Aquasp102** [GaryOderNichts/moonlight-wiiu#4]
I've been trying to use this program for the past week at least, and it never ended up working consistently for me. Usually what ends up happening for me is when the Moonlight stream starts on my Wii U, it works fine on the main Steam Big Picture home, but when I enter my library or the Steam store, it freezes. I don't know exactly why this happens, but I noticed that the freezing tended to happen when there were large amounts of activity on the screen happening. In the case of the store and library, it may be because of all of the images of games are too much for the program to handle. I did also notice that the program seems to run fine when on other simplistic menus, like in a few games that I play. Though even when I am in a few games, the screen tends to flash, most likely because there's more happening at once compared to the Steam Big Picture menu. And I'm not sure if it's a connection issue either, as I've tested Moonlight on my tablet and it seems to work just fine. I even have my Wii U connected to ethernet. I've tried multiple things to be able to fix it. I've tried adjusting the frame rate, resolution, bitrate, and none of them seemed to fix this issue. I've also tried lowering the versions of GFE that I have, and this issue still seems to happen. I would also try switching the default program that boots up to not be Steam, but there doesn't seem to be clear instructions on how to do this. Does anyone by chance know why this is happening? I honestly have no idea why this issue seems to be happening for me.

**Comment by GaryOderNichts** [comment]
Your bitrate is probably too high and your network connection can't keep up (see the newly added [Troubleshooting section](https://github.com/GaryOderNichts/moonlight-wiiu#troubleshooting)).
You can also try the latest [v1.6 release](https://github.com/GaryOderNichts/moonlight-wiiu/releases/tag/wiiu-v1.6) which comes with networking improvements.
