### ISSUE TITLE
Connection terminated with error: 5

### ISSUE THREAD

**Issue by one-and-only** [GaryOderNichts/moonlight-wiiu#48]
No matter which game/app I add as an application in Sunshine server, I always get "Connection terminated with error: 122" on my Wii U, despite having a very low resolution/bitrate to begin with. I've tried all sorts of bitrates, resolution, fps, etc. on my Wii U and various different settings in Sunshine to no avail. I appreciate your help in getting this resolved. More information is available upon request. Thank you very much.

**Comment by GaryOderNichts** [comment]
`122` is `EMSGSIZE`. Did you modify the `packetsize` in your configuration or change the MTU of your network connection in the system settings?

**Comment by one-and-only** [comment]
> `122` is `EMSGSIZE`. Did you modify the `packetsize` in your configuration or change the MTU of your network connection in the system settings?

In system settings it is 1500 and in the config file for Moonlight it’s 1472. Is this bad?

**Comment by one-and-only** [comment]
I changed the packet size to 1280 in moonlight config and now it seems to be working. I can't exit the strem, however. Would you happen to know the input combination to disconnect the stream? Thank you :)

**Comment by one-and-only** [comment]
actually, after a little while of streaming, I get "Connection terminated with error: 5". If this is an errno, it means that there was an I/O error with the disk, right? The SD card is not locked so everything should be working fine.

**Comment by one-and-only** [comment]
I set the MTU to 1280 and that seemed to fix the issue. Thank you for your help :)

**Comment by GaryOderNichts** [comment]
You usually don't need to adjust anything packetsize/MTU related. The default `packetsize` is `1392`, which should work without changing the MTU.
