### ISSUE TITLE
Gamepad controls not working

### ISSUE THREAD

**Issue by ghost** [GaryOderNichts/moonlight-wiiu#5]
Whenver I try to play a game, the gamepad isn't inputting the controlls being pushed. Disable_gamepad is disabled in the config.

**Comment by GaryOderNichts** [comment]
Are you using Version 1.2?

**Comment by TrashBandatcoot** [comment]
Reopening this, I'm using v1.3 with gamepad_disable disabled, and no apps or games detect any input. Wiimotes don't work either.

**Comment by GaryOderNichts** [comment]
Are you sure this isn't an issue on the host side? Have you tried using moonlight on another PC / phone / ...?
