### ISSUE TITLE
Problem with last version

### ISSUE THREAD

**Issue by mrpedrotomas** [GaryOderNichts/moonlight-wiiu#6]
I have tried version 1.2 with Openstream and it connected with my pc but when I tried to start the stream it crashed on the wii u. Despite the fact that the chosen program did open.

This error however does not happen in version 1.1

**Comment by GaryOderNichts** [comment]
Try the latest [v1.6 release](https://github.com/GaryOderNichts/moonlight-wiiu/releases/tag/wiiu-v1.6) which comes with various improvements.
Your bitrate might also be too high and your network connection can't keep up (see the newly added [Troubleshooting section](https://github.com/GaryOderNichts/moonlight-wiiu#troubleshooting)).
