### ISSUE TITLE
Touchscreen for the wii u?

### ISSUE THREAD

**Issue by lengsoue** [GaryOderNichts/moonlight-wiiu#7]
As I was reading in the enchantments from someone and you replied to it as there was a touch screen working but it was not working as you wanted too, I was wandering if you could put that version up as the game I would like to play just have to tap the screen to start the game and everything is off the controller but on the current version there's no touchscreen support so I have to manually use the mouse to tap to enter the game. So is it possible to have a beta or untested version of the touchscreen version?

**Comment by windraver** [comment]
+1 I just need to click twice at the start of the game in order to get started.

**Comment by windraver** [comment]
@lengsoue I just looked through the code and the touch screen code is still there:
https://github.com/GaryOderNichts/moonlight-wiiu/blob/master/src/input/evdev.c

I however don't know if it is implemented or if its working or how to enable it yet. Still reading through the code.

**Comment by GaryOderNichts** [comment]
@windraver That's the evdev touchscreen code used on PC. It's still in there since moonlight-wiiu is based on moonlight-embedded. It won't work on the Wii U though.

**Comment by lengsoue** [comment]
So it's not possible to get touchscreen support on the moonlight wii u then, so while in the announcement you stated you placed a basic touchscreen solution but it probably did not work at all as you took it down then?

**Comment by GaryOderNichts** [comment]
I don't think I have that code anymore. I would need to rewrite it.

**Comment by lengsoue** [comment]
If it's not too much work and you have time could you rewrite it, if it's too much work or you don't have time I can wait or you don't have to do it, as it's nothing I need as soon as possible just something that could help it to be more interactive and some other people might like and want to use it.

**Comment by GaryOderNichts** [comment]
Added in version 1.3
