### ISSUE TITLE
No longer working with latest GeForce experience

### ISSUE THREAD

**Issue by manaboy** [GaryOderNichts/moonlight-wiiu#8]
I can not for the life of me get anything to load on any version of moonlight Wii u, I am using the latest version of GeForce experience, when I go to load a game the Wii u would go to a blank screen with no sound, but on my pc the game has actually launched, so the pc is receiving the command. The WiiU hasn't crashed as when I press the home button it returns me to homebrew launcher.

Hope there could b a fix for this as I've been using the android, Nintendo switce and pc version without any issues, just my brother has a old Wii u and I wanted to give him the chance to make use of it playing latest games from my pc.

**Comment by manaboy** [comment]
Is this project still alive?

**Comment by Special-Niewbie** [comment]
With the latest Geforce Experience, I confirm that it doesn't work anymore (the symphtoms are exactly as was explained in this main top topic); kindly we need to waiting for @GaryOderNichts that will have time to fix it.
Inmeantime @manaboy you can keep the latest drivers versions of Nvidia, and unistall just only Geforce Experience, by following this guide here, from CrisMod: https://gbatemp.net/threads/moonlight-wii-u.585995/page-7#posts

**Comment by RodrigoTomeES** [comment]
Hi,

With the last version of the Moonlight Wii U you can use the lastest version of GeForce Expirience but you need to have the computer screen on and also there is issues with the connection I will try to downgrade to 3.21.

**Comment by GaryOderNichts** [comment]
This should work with the new [v1.6 release](https://github.com/GaryOderNichts/moonlight-wiiu/releases/tag/wiiu-v1.6) which also comes with various improvements.
If GFE still doesn't work, you can try using [sunshine](https://github.com/LizardByte/Sunshine/).
